name: bubble
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  appwrite: ^9.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.5
  get_it: ^7.2.0
  injectable: ^1.5.4
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  objectbox_generator: ^2.0.0
  connectivity_plus: ^3.0.4
  intl: ^0.17.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.1.0
  uuid: ^3.0.7
  sprintf: ^7.0.0
  flutter_switch: ^0.3.2
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.7.0
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  timeago: ^3.3.0
  cached_network_image: ^3.2.3
  encrypt: ^5.0.1
  fl_country_code_picker: ^0.1.2
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  google_sign_in: ^6.1.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  # hc1XFYtxPhLZBoXH_3jQ2A770AsYfyZWexspsTRe

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/

  fonts:
    - family: KoHo
      fonts:
        - asset: assets/fonts/KoHo-Regular.ttf
          weight: 400
        - asset: assets/fonts/KoHo-Medium.ttf
          weight: 500
        - asset: assets/fonts/KoHo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KoHo-Bold.ttf
          weight: 700
